title: AWS DVA-C02 Skills
description: AWS Certified Developer - Associate skill knowledge base
remote_theme: just-the-docs/just-the-docs
search_enabled: true
aux_links:
  GitHub Repository: https://github.com/gb06501/dva-c02
